---

- name: Create Kickstart file for OSD Servers
  copy:
    force: yes
    dest: "{{ file_path }}/{{ item.hostName }}/KS.CFG"
    content: |
      vmaccepteula
      clearpart --firstdisk=local --overwritevmfs
      install --firstdisk=local --overwritevmfs
      rootpw {{ root_password }}
      network --bootproto=static --addvmportgroup=1 {% if global_vlan_id | int > 0 %}--vlanid={{ global_vlan_id }} {% endif %}--ip={{ item.esxi_ip }} --netmask={{ global_netmask }} --gateway={{ global_gw }} --nameserver={{ global_dns1 }} --hostname={{ item.hostName }}
      reboot --noeject
      %firstboot --interpreter=busybox
      vim-cmd hostsvc/enable_ssh
      vim-cmd hostsvc/start_ssh
      vim-cmd hostsvc/enable_esx_shell
      vim-cmd hostsvc/start_esx_shell
      esxcli system module parameters set -m tcpip6 -p ipv6=0
      esxcli network ip set --ipv6-enabled=false
      esxcli system ntp set --server={{ global_ntp1 }} --server={{ global_ntp2 }}
      esxcli network ip dns server add --server={{ global_dns2 }}
      esxcli system ntp set --enabled=true
      esxcli system ntp start
  with_items:
    - "{{ hosts }}"


